### ISSUE TITLE
pod 'FileProvider' error

### ISSUE THREAD

**Issue by perwyl** [amosavian/FileProvider#2]
when i install it via pod, i am unable to construct `WebDAVFileProvider`

```
WebDAVFileProvider cannot be constructed because it has no accessible initializers

```

Adding the source folder to the project is file.

**Comment by amosavian** [comment]
Please update to version 0.3.0 and check again thanks @perwyl

**Comment by perwyl** [comment]
updated and the problem persist.  [Check out the sample project here](https://github.com/perwyl/FileProviderDemo)

**Comment by amosavian** [comment]
Thank you. Please update to 0.3.2.
It was about scope modifiers rather than framework project. I added `public` modifier to all variables and init methods and now it's accessible via pod. checked and it works!
By the way you don't need to create different classes and views for each filesystem. All of them are conforming to `FileProvider` protocol and you can declare variable as that:

    var fileProvider: FileProvider
    fileProvider = WebDAVFileProvider(baseURL: NSURL(string: path)!, credential: credential)

and in another point change it to local one!

    fileProvider = LocalFileProvider()

in this case you need to use `createSymbolicLinkAtPath()` which is only available in LocalFileProvider and isn't declared in `FileProvider` protocol, you should downcast variable:

    (fileProvider as? LocalFileProvider)?.createSymbolicLinkAtPath(path, withDestinationPath: destPath, completionHandler: nil)

**Comment by perwyl** [comment]
The update is pretty fast @amosavia!

```
1: var fileProvider: FileProvider!
2: fileProvider = WebDAVFileProvider() as! FileProvicer   //Need to cast it :)
```
