### ISSUE TITLE
let documentsProvider = CloudFileProvider(containerId: nil)

### ISSUE THREAD

**Issue by liyoro** [amosavian/FileProvider#34]
when run，

let documentsProvider = CloudFileProvider(containerId: nil)

break and The following log

assertion failed: LocalFileProvider.init(containerId:) is not recommended to be executed on Main Thread.: file /Users/xxx/Pods/FileProvider/Sources/CloudFileProvider.swift, line 55

What the problem？thanks！

**Comment by amosavian** [comment]
This not a problem, it's by design. Apple doesn't recommend initializing iCloud container for the first time from main thread. You can run the initializer in DispatchQueue, or set `CloudFileProvider.asserting` property to `false` in case you don't mind if you app freezes in some cases.

Check Apple documentation for more information: https://developer.apple.com/reference/foundation/filemanager/1411653-url

**Comment by liyoro** [comment]
thank you！
