### ISSUE TITLE
View files in web browser

### ISSUE THREAD

**Issue by ialimz** [amosavian/FileProvider#5]
Hi Amir ;
more power and proud that are country mate:)
I am developing a file manager and almost done , I added your pod to my project for use it as Wifi transfer but I don't have any idea about it, can you guide me a a little?

**Comment by amosavian** [comment]
Hi @ialimz ,
It's and WebDAV client (not server) library. WebDAV is inaccessible via browser by design. In this case you can use `GCDWebUploader` class in [swisspol/GCDWebServer](https://github.com/swisspol/GCDWebServer) library. It also has `GCDWebDAVServer` class in case you know want a WebDAV server.

**Comment by ialimz** [comment]
@amosavian thanks for quick and correct answer;
you saved my day bro
