### ISSUE TITLE
How to determine if an item exists on a provider?

### ISSUE THREAD

**Issue by jhoughjr** [amosavian/FileProvider#80]
I dont see anything in the protocol to see if an item exists.

**Comment by amosavian** [comment]
I didn't implement `fileExists()` method by intention. Checking existence of a file before doing an operation (like copy or move) may lead to [race condition](https://en.wikipedia.org/wiki/Race_condition). I **strongly** recommend you to avoid checking and call operation method (copy, move , etc) directly and let it fail if file doesn't exist!

If you intend to check file existence for other proposes (I can't imagine why), You can use `attributesOfItem(path:, completionHandler:)` method. It will return a `FileObject` in completion handler if file exists otherwise it will be nil.
