### ISSUE TITLE
Example to save in iCloud documents

### ISSUE THREAD

**Issue by Pirokar** [amosavian/FileProvider#98]
Can you give me example to save any file to iCloud documents, please?

This is my code (screenshot): http://prntscr.com/jr7sb1
But, as you can see in the screenshot, it's getting the error for me NSCocoaErrorDomain - code: 262

**Comment by amosavian** [comment]
You must create source file url using `URL(fileURLWithPath:)` instead of `URL(string:)`.

Btw, completion handler runs on background thread and presenting UI elements is not recommended there. Either you must present `UIAlertViewController` inside `DispatchQueue.main.async()` or use delegate methods as they are guaranteed to be run on main thread.

There is a sample implementation: https://github.com/amosavian/FileProvider/blob/master/Docs/Sample-iOS.swift

**Comment by amosavian** [comment]
I forgot to mention you must **not** pass complete path but relative destination path. e.g:

```swift
let localURL = URL(fileURLWithPath:"/Users/user/file.txt")
documentsProvider?.copyItem(localFile: localURL, to: "/destination.txt", completionHandler: nil)
```
